name: "Release by Tag"

on:
  push:
    tags:
      - "v**"
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.vars.outputs.version }}
    steps:
      - id: vars
        run: |
          VERSION=$(echo ${{ github.ref }} | sed -e 's/refs\/tags\///' | sed -e 's/refs\/heads\///')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - uses: natsuneko-laboratory/create-unitypackage@v2.2.0
        with:
          package: Assets/NatsunekoLaboratory/HierarchyStalker/package.json
          output: dist/AnimationAutoAssignment-${{ needs.setup.outputs.version }}.unitypackage

      - uses: actions/upload-artifact@v2
        with:
          name: AnimationAutoAssignment
          path: dist/
